/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c2688e4c9c0c1df7aa0137eb6a4295de)
interface __BaseEnv_Env {
	GAME_ANALYTICS: AnalyticsEngineDataset;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
